apiVersion: apps/v1
kind: Deployment
metadata:
  name: thl-khoaluan-backend
spec:
  selector:
    matchLabels:
      app: thl-khoaluan-backend
  replicas: 2    
  template:
    metadata:
      labels:
        app: thl-khoaluan-backend
    spec:
      containers:
      - name: thl-khoaluan-backend
        image: ghcr.io/chidung091/thl-khoaluan-qldrl:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3003

